name: nbt_codec
version: 1.1.0
author: Thomas Caserta <tom@caserta.co.uk>
description: NBT Codec is a Minecraft NBT tag reader and writer that works in both browser and server.
homepage: https://github.com/TomCaserta/dart_nbt_codec
documentation: http://tom.caserta.co.uk/documentation/nbt_codec/index.html
dependencies:
  archive: '>=1.0.16'
  browser: any
  collection: '>=0.9.1'
  fixnum: '>=0.9.0'
  unittest: any
